### PR TITLE
Change Moldovan locale code for Moldovan 'ro_MD' 

### PR DESCRIPTION
**Pull request by fmneto**
(Related to elementary/terminal#598)

This is the equivalent for elementary code (see https://github.com/elementary/terminal/pull/599)

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
It looks like the way you've modified the line wrapping if causing the build to fail

Also, please don't forget to update the po and LINGUAS files in `extra` :)

**Comment by fmneto** [comment]
> It looks like the way you've modified the line wrapping if causing the build to fail
> 
> Also, please don't forget to update the po and LINGUAS files in `extra` :)

Sent in a new commit; this should be fine now :)

**Comment by fmneto** [comment]
Eh, I didn't touch anything outside the po folder... :(

**Comment by fmneto** [comment]
Not sure if there's anything for me to do. Seems to be some problem with installing dependencies. Repo misbehaving maybe?

I don't know. I'll wait for a bit and try again.

**Review by ryonakano — APPROVED** [review]

**Review by tintou — APPROVED** [review]

**Comment by fmneto** [comment]
Yay!

**Pull request merged**
