### PR TITLE
[GTK4 Prep] Create FileView Context Menu Items using GLib.MenuModel

### PR DESCRIPTION
**Pull request by colinkiama**
Completes the "Replace Gtk.MenuItem with GLib.MenuModel" task in #1157

### CODE REVIEW

**Comment by colinkiama** [comment]
A side effect I've noticed with this change is that keyboard accelerators are no longer displaying in the FileView context menus. Is this what was expected to happen?

**Review by danirabbit — CHANGES_REQUESTED** [review]
Just one thing that looks off, otherwise seems like everything is good. Nice work! That was a lot of refactoring!

**Comment by danirabbit** [comment]
@colinkiama Ah so looking at it before it looks like the menu items with accels didn't pass a path argument and you've added a path to the menuitems here? For example the New Branch item will show the accel if you change the detailed action to:

```
                GLib.Action.print_detailed_name (
                    MainWindow.ACTION_PREFIX + MainWindow.ACTION_NEW_BRANCH,
                    ""
                )
```

**Comment by colinkiama** [comment]
I've fixed the issue with the accelerators by using the "accel" attribute supported by GLib.MenuModel.

**Review by danirabbit — APPROVED** [review]
works for me. Nice work!

**Pull request merged**
