### PR TITLE
Implement choose project dialog and use for new-branch action

### LINKED ISSUE #1005: New Branch Dialog: offer a dropdown if focused project is unknown
## Problem

When creating a new branch, if Code isn't able to determined the focused branch we get a warning dialog explaining that we must first open a project etc.

## Proposal

Instead, we could offer a dropdown listing the available projects so that the user could choose the one they meant to create a branch for

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #1005

### CODE REVIEW

**Comment by jeremypw** [comment]
ChooseProjectDialog

Maybe do not need both lines of text?

**Comment by danrabbit** [comment]
If we're creating a separate UI anyways, maybe we should stick this as a combobox on the headerbar to solve #991?

**Comment by jeremypw** [comment]
@danrabbit OK, but there are some design questions to answer:

* Where on the headerbar should it appear
* Should it hide or become insensitive if no git projects are loaded - or if only one project is loaded.
* Should it default to the first (or last) opened project if there are  multiple projects but no documents opened?

**Comment by danrabbit** [comment]
@jeremy:

* My inclination would be to put it at the very start of the headerbar to imply that it effects every action in the application, including others that we may move to the headerbar
* Yeah, probably it would make sense to hide for now if there are no projects loaded, but it would make sense to have it when only one project is loaded since it still does indicate the active project.
* My inclination would be that we try to keep it updated with the most recently active project. Basically whatever our guess would have been before, we could do that logic here pro-actively instead of waiting until an action is taken. So I guess we would want to update that when we change the focused document?

**Comment by jeremypw** [comment]
Closing in favour of #1023

**Pull request closed without merging**
