### PR TITLE
Add brackets completion by default

### PR DESCRIPTION
**Pull request by danrabbit**
This plugin got majorly better recently

### CODE REVIEW

**Comment by tintou** [comment]
I'm generally not a fan of completing features as it's invasive and prevents linear coding

**Comment by jeremypw** [comment]
I am also against making an intrusive feature on by default (at least until it can guess the writers intention 99+% if the time)

**Comment by danrabbit** [comment]
Gonna close this since there's objections and we've identified some issues with the bracket completion

**Comment by cassidyjames** [comment]
Reopening to fix #667

**Comment by tintou** [comment]
Wow, this has been reopened after objections, got 0 discussion, 0 tests and breaks the app :clap:

**Comment by cassidyjames** [comment]
@tintou objections from 16 months ago before major efforts to improve the plugin. Instead of passive-aggression, could you point out what is broken so we can fix it?

**Pull request merged**
