### PR TITLE
Removing toggling of terminal button visibility for #761

### PR DESCRIPTION
**Pull request by tmullender**
Meant as a fix for #761 

This makes the terminal button visible once the plugin is enabled irrespective of whether a document is open or not.

This could have an impact on other plugins as the bottom bar is now visible when no documents are selected.  I have not found any impacts on the plugins that are part of this repository, are there plugins available that are not part of this repo?

### CODE REVIEW

**Comment by jeremypw** [comment]
I believe it is intended that the terminal plugin will be removed in the future in favour of more focused build/install functionality.

I am not sure why you would need to toggle the terminal when there are no documents open anyway.  In this PR, the bottombar closes when switching to the welcome page so you have to toggle it on again to see it.

I can see there is an inconsistency in that the search icon remains visible when the welcome page is shown although it is insensitive.

Flagging for design team comment.

**Comment by tmullender** [comment]
Thanks Jeremy.  I played with making the button insensitive when switching to the welcome page but it felt wrong to close the terminal when closing a document.  I'll wait for the design team's comments

**Comment by jeremypw** [comment]
@tmullender You will probably need to resolve the conflicts before the UX team will review.

**Review by danrabbit — APPROVED** [review]
Sorry for taking so long to review! Fixed conflicts and lgtm. Thanks for this fix!

**Pull request merged**
