### PR TITLE
Copy current line when no selection

### PR DESCRIPTION
**Pull request by davidmhewitt**
To match the Ctrl+X cuts a line when there's no selection functionality.

### CODE REVIEW

**Comment by jeremypw** [comment]
Needs UX decision as to what the default behaviour should be and how (if) to expose any setting to the user.

**Comment by cassidyjames** [comment]
As much as I hate adding more fiddly knobs… would it make sense to put these under a "Smart copy/paste" toggle in the settings? To me it makes sense to have on by default, because it's a low-risk mistake if you hit the wrong key (you can just undo). But I can understand some resistance to not doing what you'd expect.

**Comment by jeremypw** [comment]
Just to note: you cannot undo pressing Ctrl+C instead of Ctrl+V - the contents of the clipboard are overwritten and undo does not reverse this.

A refinement might be to have smart copy/cut work only when there is nothing pending in the clipboard but that might be considered to be too 'smart' and leads to unpredictable behaviour.

**Comment by jeremypw** [comment]
@cassidyjames :  Can you suggest a string that would meet with approval?

**Comment by cassidyjames** [comment]
@jeremypw I'm working on that now. :smile:

**Comment by cassidyjames** [comment]
@jeremypw @davidmhewitt and @elementary/ux feel free to check #611. If we're going to add and support this feature, I think something like that is the way to do it. I first tried with a dim label (like we've been doing in System Settings lately), but the smaller design of the dialog made it feel really awkward and lopsided. Input/suggestions welcome, though.

**Pull request merged**
