### PR TITLE
Add help action linked to Github wiki

### LINKED ISSUE #874: Add option to view all keyboard shortucts available in the app
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

I don't know if there's a faster way to do something with the keyboard instead of the mouse because I don't know the keyboard shortcuts available in the app.

**Describe the solution you'd like**

An additional entry under the app's settings called "Keyboard Shortcuts". Selecting it should open a window that displays all the keyboard shortcuts available in the app. We should be able to continue working in code while the keyboard shortcuts window is still open.

**Existing work**

When you press the super key, the elementaryOS shows a list of keyboard shortcuts available. Shortcuts are grouped in sections 
that describe the context of their usage.

**Additional context**
https://elementaryos.stackexchange.com/questions/17256/what-keyboard-shortcuts-are-available-in-code

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #874 

A page has been added to the wiki listing the available shortcuts.  A link to StackExchange questions on Code has also been added to the wiki homepage.

### CODE REVIEW

**Comment by danrabbit** [comment]
I would really prefer not to send users to the web. Especially since this page will likely not stay up to date with the code base.

**Comment by jeremypw** [comment]
Yes, this was really a stop gap pending development of some local system for apps to make their shortcuts discoverable.  I would note that Files already sends users to StackExchange on pressing F1.  Not sure atm what other native apps do (if anything)

**Comment by jeremypw** [comment]
I thinks pressing `F1` should do *something* though.

**Comment by cassidyjames** [comment]
Yeah I’m :-1: on sending folks to the web, too. If we want to show all shortcuts somewhere, it should be determined by the actions in the app itself. I’m also :-1: on Files sending people to a (third-party) website with a keypress, but I’ll file that separately. :wink:

**Comment by jeremypw** [comment]
OK, withdrawing pending a better solution.

**Pull request closed without merging**
