### PR TITLE
MonitoredRepository: Allow Changing Branch with Untracked Files

### PR DESCRIPTION
**Pull request by Marukesu**
Untracked files aren't affected by branch changes, ignore thoses when checking for uncommitted changes.

### CODE REVIEW

**Comment by jeremypw** [comment]
What kind of untracked files are you thinking of? I find that untracked files (even new ones) that are matched by a line in the `.gitignore` file do not block changing branch.

**Comment by jeremypw** [comment]
If Git has not been instructed to ignore a file then maybe it is the correct behaviour to block changing branch? I think this is what happens on the command line?

**Comment by Marukesu** [comment]
> What kind of untracked files are you thinking of? I find that untracked files (even new ones) that are matched by a line in the `.gitignore` file do not block changing branch.

Untracked files are the files that exists on the working directory that aren't specified on `.gitignore` neither staged for commit.

For example, doing ` touch dummy.txt` will create an untracked file, and that would block the branch submenu on master. However, `git switch` and `git checkout -b` still work in this case.

**Comment by jeremypw** [comment]
Ah yes, you are right untracked files for not block branch change on the commandline. So this PR is a good idea.  I'll review.

**Review by jeremypw — APPROVED** [review]
Does the job - nice fix!

**Pull request merged**
