### PR TITLE
FolderManager: use git emblem icons

### LINKED ISSUE #1462: Git status icons use user-namespace icons
### What Happened?

git status icons in the sidebar use `user-` namespace icons.

### Steps to Reproduce

Screenshot from 2024-08-28 15 59 30

### Expected Behavior

There are `emblem-` namespace icons that are a drop-in replacement that should be used instead

### OS Version

8.x (Early Access)

### Software Version

Compiled from git

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by danirabbit**
Fixes #1462 

These were added to icons several years ago https://github.com/elementary/icons/pull/1025

### CODE REVIEW

**Comment by tintou** [comment]
otherwise this looks good!

**Comment by jeremypw** [comment]
Can these icons be made available in Granite as both Code and Files use them and already have that dependency?

**Comment by danirabbit** [comment]
Honestly it might be kinda niche for Granite, but resourced here in the latest commit!

**Review by jeremypw — APPROVED** [review]

**Comment by jeremypw** [comment]
Oops - seems to be a problem with CI - but otherwise approve.

**Comment by danirabbit** [comment]
@jeremypw looks like I had made a typo 😅 should be ready to re-review

**Review by jeremypw — APPROVED** [review]
New icons appear as expected.

**Pull request merged**
