### PR TITLE
Add Accels for keyboard shortcuts

### PR DESCRIPTION
**Pull request by cassidyjames**
WIP, help wanted :stuck_out_tongue:

### CODE REVIEW

**Comment by jeremypw** [comment]
You could add an accel tooltip to the modelbutton.

**Comment by cassidyjames** [comment]
@jeremypw UI-wise I'd prefer the inline shortcut label like we do in Terminal

**Comment by jeremypw** [comment]
@cassidyjames How's this? I expect some tweaking of margins etc will be required, but it basically works.

**Comment by cassidyjames** [comment]
I think we'd want to retain the menu styling, whereas this adds some padding and doesn't look like other menus.

image

image

**Comment by jeremypw** [comment]
OK, so the main differences to be resolved are:
* spacing of menuitems
* Font of menuite, text
* Select on hover

**Comment by jeremypw** [comment]
Appearance similar now:

# PR
accel_app_menu

# MASTER
master_app_menu

**Comment by jeremypw** [comment]
Should be able to use Granite.AccelLabel to simplify this?

**Comment by jeremypw** [comment]
@cassidyjames  Is this PR still needed?  There are what look like Granite.AccelLabels in that menu now:

Screenshot from 2020-03-13 19 06 14

**Comment by cassidyjames** [comment]
Yeah this can be closed. Thanks for following up!

**Pull request closed without merging**
