### PR TITLE
ChooseProjectButton: valign center

### PR DESCRIPTION
**Pull request by danrabbit**
Instead of hard coding a margin, we can center align for the same effect

### CODE REVIEW

**Comment by jeremypw** [comment]
I used margins after @hanaral 's comment about the buttons height not matching the equivalent buttons in the FormatBar.  I'll check whether this changes that (or perhaps it doesnt matter).

**Comment by jeremypw** [comment]
Taller button than FormatBar

ValighChooseProject

**Comment by jeremypw** [comment]
Sorry - pressed wrong button :facepalm:

**Comment by jeremypw** [comment]
Actually I can't really see the difference

**Comment by danrabbit** [comment]
The headerbar isn't forced to be larger in this branch

**Pull request merged**
