### PR TITLE
Release 7.1.0

### PR DESCRIPTION
**Pull request by jeremypw**
- [x] Fix any regressions 
 - - [x] Occasional unexpected "Cannot save dialog" Should be fixed by #1309
 - - [x] Pressing `<Ctrl>F` can reload a previous search unexpectedly.  Fixed by #1335
 - - [x] Spurious external change dialogs  since recent commits Fixed by #1354 
 - - [x] Unexpected clearing of search  entry under some conditions. Fixed by #1359
- [x] Merge updated metainfo from  #1303 
- [x] Merge updated metainfo from  #1315
- [x] Merge updated metainfo from  recent merges
- [x] Merge #1320, if possible
- [x] Finalize release date

### CODE REVIEW

**Comment by jeremypw** [comment]
I'd like #1309 to be merged before release so there is consistent use of dialogs not infobar.

**Comment by jeremypw** [comment]
It would be nice if #1320 could be merged too as this is a really annoying issue.

**Comment by jeremypw** [comment]
Just noticed a new regression which needs looking into before release.

**Review by zeebok — COMMENTED** [review]
The release tag date is a bit old at this point but I think this is ready for review/approval unless you want a little testing done for the full release

**Comment by jeremypw** [comment]
@zeebok  Yes, I wanted to do a few days testing before updating the release date and marking ready for review. Probably be ready beginning of next week.  Need to update the metainfo too.

**Comment by jeremypw** [comment]
@zeebok I only include issues that were present in the last released version of Code or that have some significance to the user (like new/changed features/appearance).  Things like correcting problems with a recent unreleased commit or code cleanups are not included.  I think the regressions were all caused by unreleased commits so I did not include them.  If I have missed something that changed something in the last released version please let me know.

**Pull request merged**
