### PR TITLE
Several improvements to bracket completion logic

### LINKED ISSUE #308: Brackets completion over-agressively removes characters
Looks like fallout from #31. If I backspace a quote that's next to another closing bracket, the plugin also erroneously removes the unrelated bracket.
gifout

### LINKED ISSUE #309: Quote completion should skip over matching closing quotes
One awesome feature of Atom that keeps the bracket completion out of my way is that it is smart about when to draw a closing bracket/quote character. For example, if you manually type `"foo"`, it knows that the last `"` you typed is the same as the one it autocompleted for you, so it just passes over it without duplicating it. 

This also means you don't have to do arrow key gymnastics to write more naturally, even with bracket/quote completion on.

### LINKED ISSUE #344: Brackets completion interferes with compose key
When I'm trying to type my name on a copyright header, it ends up as `For'e'` instead of `Foré` because bracket completion doesn't know about the compose key :p

### PR DESCRIPTION
**Pull request by davidmhewitt**
Fixes #344 
Fixes #309 
Fixes #308 

Most of these fixes were pretty interwoven, so it's all ended up in one diff.

### CODE REVIEW

**Comment by davidmhewitt** [comment]
Marking as WIP since I seem to have introduced a crash somewhere

**Comment by davidmhewitt** [comment]
Seems like the crashing issues I was having are a conflict with the highlight word selection plugin. Not sure what's up yet, will have to investigate further.

**Comment by davidmhewitt** [comment]
I believe the crashes will be resolved after merging #430 , so that should be reviewed and merged first. Marking as blocked for now.

**Comment by danrabbit** [comment]
I can confirm that this fixes #308, #309, and #344 :)

**Pull request merged**
