### PR TITLE
Add custom elementary syntax styles

### LINKED ISSUE #29: Selected text and highlighted matching brackets are impossible to differentiate.
We either need to:
a) Disable highlighting matching brackets when other pieces of text are selected.
b) Have a different style for highlighting matching brackets.

Launchpad Details: [#LP1457744](https://bugs.launchpad.net/bugs/1457744) Lewis Goddard - 2015-05-22 05:50:46 +0000

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/44841685-selected-text-and-highlighted-matching-brackets-are-impossible-to-differentiate?utm_campaign=plugin&utm_content=tracker%2F61917289&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F61917289&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by micahilbery**
This adds custom styles for syntax highlighting based on the elementary color palette.

fixes #29

### CODE REVIEW

**Comment by hanaral** [comment]
@micahilbery is this supposed to fix the long-standing issue of the highlight cursor colour in the solarised theme being the same?

**Comment by micahilbery** [comment]
@hanaral If you're talking about the bracket highlighting and selection highlighting being the same yes this fixes that.
selection-vs-bracket-highlighting

**Comment by jeremypw** [comment]
> If you're talking about the bracket highlighting and selection highlighting being the same then yes this fixes that.

It looks like that the selection style is applied in preference to the bracket-match style so brackets that are both matching and selected only get the selection style.  Presumably this behaviour is controlled by `gtksourceview-4`.

**Review by danirabbit — DISMISSED** [review]
These are pretty cool! The dark style is especially really pretty! I'm going to try to use these more daily and see where I notice any issues :)

One thing I noticed is that we're missing some fields that are provided by the `classic` style. Namely the git diff colors for the gutter: https://github.com/GNOME/gtksourceview/blob/master/data/styles/classic.xml#L110

**Comment by jeremypw** [comment]
@micahilbery Will you be addressing the issue with gutter colors?

**Comment by micahilbery** [comment]
Yes, I hope to work on it today. Sorry for the delay. My day job and seasonal plans have pretty well wiped out my free time.

**Comment by micahilbery** [comment]
I've updated the style so that we match classic and tested the git gutters afaict everything seems to be working as it should. Sorry this took me so long to get too.

**Comment by jeremypw** [comment]
Thanks - I'll try these out for a while to see if any issues arise.

**Comment by jeremypw** [comment]
I've merged this PR into my 'merge-dev-fixes- branch for dog-fooding.

Do far I've noticed that it is harder to see the selected text, especially for solarized-light:

ElementarySolarizedLightSelectedText

ElementarySolarizedDarkSelectedText

However, it is easier to distinguish selected brackets from highlighted brackets.

Is there a reason why selected text in the dark version is inverted in color whereas in the light version it isn't?

**Comment by jeremypw** [comment]
@micahilbery I'm inclined to merge this as @danirabbit is :+1:  Just one question: "Follow System Style" uses the standard "solarized-light" and "solarized-dark" styles - is that intended?

**Review by jeremypw — APPROVED** [review]
I am going to go ahead and merge this as tweaks to themes can be done after further feedback.

**Pull request merged**
