### PR TITLE
Add symbol filter to outline pane

### PR DESCRIPTION
**Pull request by jeremypw**
The is a speculative step towards fixing issues such as #933, #809 and generally increasing the utility of the symbol pane over just searching the text.

 - [x] Add a toolbar header
 - [x] Search Entry in toolbar (currently only search within)
 - - [ ] Option to search start only  (?)
 - [x]  Add Filter menu
 - - [x] Add SymbolType enum and classify Vala and C symbols with symbol type 
 - - [x] Allow filtering by symbol type
 - - [x] Add Action bar to popover for bulk select/deselect filter options
 - - [x] Better icon for filter menu?
 - [ ] Choosing e.g. "method" should automatically choose "class" (or "class" always included in filter?)
 

Note: To show class methods both the "Class" and "Methods" selections must be active.

### No filtering:
Screenshot from 2023-03-21 11 55 57

### Filtering class properties
Screenshot from 2023-03-21 11 56 27

### Searching for text "filter"
Screenshot from 2023-03-21 11 57 24

### CODE REVIEW

**Comment by jeremypw** [comment]
### No filtering:
Screenshot from 2023-01-24 16 09 27

### Filtering class properties
Screenshot from 2023-01-24 16 10 11

### Filtering methods and properties containing text "filter"
Screenshot from 2023-01-24 16 30 00

**Comment by jeremypw** [comment]
Looks like the regression is due to recent changes to master :disappointed: not this PR.

**Comment by jeremypw** [comment]
Regression now fixed by #1254.  Leaving this as draft as that PR should be prioritised.

**Review by zeebok — APPROVED** [review]
It appears to work as intended!

**Comment by jeremypw** [comment]
@danirabbit Is this something worth progressing? I wasn't sure what icon should be used for the "Select all" button (or whether such a button is needed)

**Comment by danirabbit** [comment]
@jeremypw sorry for taking a while to follow up on this! I pushed a commit with the filter icon we're using in Mail and fixing the sidebar background styles.

I think for the popover I would just a regular menu here and use regular text menu items for the "select all" and "deselect" all items since those are probably more clearly communicated with text and we're not particularly constrained for space in a menu

**Review by danirabbit — APPROVED** [review]
Works as expected afaict. Nice job :)

**Pull request merged**
