### PR TITLE
Sidebar shows incorrect project structure #818

### PR DESCRIPTION
**Pull request by Otofuji**
Hello! In this pull request, I'm trying to address issue #818. Per my investigation, ProjectItemFolder detects when the issue occurs, but there is no handling to it. Solution is to close the project folder upon error catch.

### CODE REVIEW

**Comment by jeremypw** [comment]
Thanks for your first contribution. This is a simple but limited solution that will only work on git repositories.  It does not work on other types of project folder.  The main issue seems to be that although Code detects renaming of files and folders inside the project folder, it does not detect (or does not react to) changing the project folder name.  Either the project folder should close or, better, it should just be renamed in the sidebar - even if it is not a git repository.

**Comment by jeremypw** [comment]
@Otofuji Will you be able to progress this PR to make it work with project folders other than git repos?

**Comment by Otofuji** [comment]
@jeremypw Hello! Due to personal reasons, I am unable to collaborate right now. I hope to be able to collaborate further when this personal situation be resolved. Thanks for comprehension!

**Comment by jeremypw** [comment]
@Otofuji That's OK.  Perhaps some other developer will progress this.  I hope your situation resolves soon.

**Comment by jeremypw** [comment]
Converted to draft as not currently under active develoipment and will conflict with other proposed changes to git repo handling.

**Comment by danrabbit** [comment]
I'm going to close this since there hasn't been any movement on it since last year. Please feel free to reopen if you can pick up work here again

**Comment by jeremypw** [comment]
I'll probably create a new PR based on this and updated Code at some point.

**Pull request closed without merging**
