### PR TITLE
Remove plugin set option

### PR DESCRIPTION
**Pull request by jeremypw**
Towards addressing #1322 

A separate PR is required to remove the option from the man page,

### CODE REVIEW

**Comment by danirabbit** [comment]
@jeremypw does this still require a separate PR since #1325 was merged?

**Comment by jeremypw** [comment]
#1325 Did not alter the man page only changed the way it is installed so yes, after code support for this option is removed by this PR, the manpage needs updating.  I could do it here as well though.

**Comment by jeremypw** [comment]
Oh, I cannot amend the man page here - it targets the deb-packaging branch.

**Review by Marukesu — APPROVED** [review]
LGTM.

**Pull request merged**
