### PR TITLE
Enhance vim emulation commands

### PR DESCRIPTION
**Pull request by mcclurgm**
Started as a fix for my issue #614.
It implements 2 new commands, lower-case "a" to insert after cursor and caret "^" to move to beginning of the indented line.
It also updates the behavior of other commands to use paragraph ends instead of display line ends, like vim does, to be more predictable.

It's a work in progress at the moment, I expect to add more stuff going forward. All my changes should be independent so you can only merge the ones you want.

### CODE REVIEW

**Comment by jeremypw** [comment]
Probably best reviewed by a Vim (plugin) user. Code style looks OK.

**Comment by jeremypw** [comment]
@mcclurgm Need to fix lint error (trailing whitespace).

**Comment by mcclurgm** [comment]
Sorry I haven't been keeping up on this. I'm working on starting to break it up into a collection of smaller, focused PRs as you requested. I've also realized issues with some of the changes in this PR (for example, moving up or down resets to the end of the line), so I think it's probably safe to discard it and I'll reimplement the changes with fixed behavior.

**Comment by jeremypw** [comment]
@mcclurgm OK, thanks.  I'll close for now.

**Pull request closed without merging**
