### PR TITLE
Adding an explicit help option

### LINKED ISSUE #689: Running the command with the -h option closes the application
I was running Code, then i opened a new Terminal and wrote `io.elementary.code -h` to get the help about the command (i was looking for where i can report an issue), but it closed the Code's window.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/76480617-running-the-command-with-the-h-option-closes-the-application?utm_campaign=plugin&utm_content=tracker%2F61917289&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F61917289&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tmullender**
Needed to avoid the exit(0) in OptionContext.print_help

Fixes #689 

This is my weekly attempt at learning a bit more vala et al.  Shout if this more annoying to you than helpful and I can just keep it to myself.

I'm not sure if I'm supposed to update the translatable strings or not, so I've separated out the commits for some clarity.  There seems to be quite a lot of changes generated, should I be trimming this down to what is required or is this just expected?

### CODE REVIEW

**Comment by davidmhewitt** [comment]
To make things easier to review, we don't add translation file changes to PRs.

Most repositories have a GitHub Actions workflow that follows up after merged PRs and makes these translation changes automatically. And if a repository doesn't have this automation, then someone from the team will do this manually.

If you could revert your translation changes, we should be able to consider this for merging.

Another handy tip:
If you put "Fixes #689" somewhere in your PR description (you'll be able to edit it), it will automatically close #689 when the PR is merged. Just a useful one for any future PRs :wink:

**Comment by tmullender** [comment]
Thanks for the help @davidmhewitt hopefully I've done what you suggested

**Comment by jeremypw** [comment]
@davidmhewitt Will you be able to review this PR?

**Comment by davidmhewitt** [comment]
Really sorry it's taken so long to come back to this! It had dropped off my radar.

I've had a bit more chance to look at this and while it fixes the issue, I think unfortunately it's just papering over a more fundamental issue with the way Code handles command line arguments as the `help` option shouldn't quit the primary instance of the application under normal circumstances.

I'll have a bit more of a look to see what the underlying problem is, but if I don't come up with anything then I'm happy with this as a workaround.

**Comment by davidmhewitt** [comment]
I've proposed an alternative fix in #913 

Thank you for your work though @tmullender , it's certainly helped with tracking down the issue!

**Comment by danrabbit** [comment]
Closing in favor of #913

**Pull request closed without merging**
