### PR TITLE
check if text_buffer is null before searching

### LINKED ISSUE #477: Segmentation fault by trying to search without any opened files
A segmentation fault is happend by trying to search without any opened files. This issue only happens when we've not opened any file from the launch of Code.
With Code 3.0 on Juno. This happens from Juno Beta1 AFAIK

## Steps to reproduce the behavor

1. Launch Code
2. Click "Find..." or press "Ctrl+F"
3. Try to click the "Find"
4. The app crashes

The log when the app crashes:

```
[FATAL 20:55:53.529395] [GLib-GObject] g_object_get: assertion 'G_IS_OBJECT (object)' failed
[FATAL 20:55:53.529521] [Gtk] gtk_text_buffer_get_iter_at_offset: assertion 'GTK_IS_TEXT_BUFFER (buffer)' failed
Segmentation fault
```

## A solution as a fix (just a suggestion)

Make the search icon and Ctrl+F insensitive if there is no file opened.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/60651286-segmentation-fault-by-trying-to-search-without-any-opened-files?utm_campaign=plugin&utm_content=tracker%2F61917289&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F61917289&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mdh34**
Fixes #477

### CODE REVIEW

**Comment by mdh34** [comment]
I can't reproduce the critical messages, however I agree that the search bar should be closed / insensitive - would that not be better off in a separate PR?

**Comment by jeremypw** [comment]
If the search becomes insensitive/closed when there is no text to search then this fix is rather redundant except as a backstop, but I have withdrawn my objection if someone wishes to merge this first.

**Comment by mdh34** [comment]
This branch *should* make the search insensitive when the welcome screen is shown, however there's a problem where after the `welcome_shown` signal is thrown on first run the code never reaches the `set_widgets_sensitive` function, something to do with the signal being cancelled

**Comment by mdh34** [comment]
Addressed changes

**Pull request merged**
