### PR TITLE
Bring developer brand colors to icons

### PR DESCRIPTION
**Pull request by micahilbery**

### CODE REVIEW

**Comment by fabiozaramella** [comment]
Nice :100:

**Comment by tintou** [comment]
I don't know how i feel about it, we're loosing the alignment with Solarized and that purple is really flashy

**Comment by cassidyjames** [comment]
I think I'm gonna close this. The purple here is a bit much and the current icons match the UI pretty well. Feel free to re-open if I'm off base!

**Comment by danrabbit** [comment]
I think I agree with Cassidy. I like the idea of the tie-in with our developer brand, but I also really like the WYSIWYG nature of using the solarized light and dark colors

**Pull request closed without merging**
