### PR TITLE
Delay asking for save location if cannot determine write access

### LINKED ISSUE #1183: Autosave of unsaved buffers not reliable
### What Happened?

https://youtu.be/LrOn42Y4aIE

This works with other editors like Atom and Sublime Text. It is an essential feature for me!

### Steps to Reproduce

1. Open Code
2. New File
3. Type "something"
4. Close Code
5. Open Code

### Expected Behavior

The typed text should be saved.

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

_No response_

### LINKED ISSUE #1256: Cancelling does not work as expected when closing project folder
### What Happened?

While autosave was "off", closed project folder while a document had unsaved changes.  A warning dialog appeared with options "Close with Saving", "Cancel" and "Save".  It would be expected that pressing "Cancel" would result in the document (and the project) not being closed, in line with what happens when closing a tab.   However, the project and document were closed and the changes lost.

### Steps to Reproduce

1. Open a project folder and at least one document within it
2. Turn off "Autosave"
3. Make some changes to the document
4. Use the sidebar context menu to close the project folder
5. When the warning dialog appears press "Cance"
6. Observe that the project folder is nevertheless closed
7. Reopen the edited document
8. Observe that the changes were lost

### Expected Behavior

Pressing "Cancel" under the circumstances described should cancel the "Close Project Folder" operation and leave the edited document(s) open.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

_No response_

### LINKED ISSUE #1272: Secure WebDav files opened from Files cannot save
If I open a file from a Secure WebDav location in Files:

"You cannot save changes to the file "<filename". Do you want to save the changes somewhere else?"

This does not happen for SMB shares and also gedit handles Secure DAVFS fine.  I'm making transition to elementaryos and this is a fairly big regression for me as I use my Nextcloud instance very heavily like this.  For now I can just use gedit but wanted to pass along the opportunity to fix Code too for what i assume is fairly common use case.

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #1272 
Fixes #1256 
Fixes #1183

 - Documents on a filesystem that does not have `FileAttribute.ACCESS_CAN_WRITE` attributes now default to writable on loading so that the infobar does not show.  The infobar only shows if creating a backup file for the document fails after actually changing the document.
 - Several methods had to be made async as a result of this change so that failed save/save as always triggers an infobar and cancels operations such as closing a window or tab.

 As in master, if the `FileAttribute.ACCESS_CAN_WRITE` attribute can be determined and is `false` then the infobar shows immediately on loading. It is an open question whether this is desirable or whether the behaviour should be the same for all documents.  An unwritable document could be opened only for reading and showing the infobar is a little irritating in that case.  Also, a writable document could theoretically became unwritable while it is open and this should be handled.  It should be relatively easy to handle that in a separate PR if this PR is accepted.

Tests:
 - Open a document on a remote non-native (e.g. WebDAV) system which is unwritable .
 - Open the parent folder as a project
 - Turn off autosave
 - Make some changes
 - Attempt to close the document by closing the tab, closing the window, closing the project etc.  
 - Attempt to force save the document with `<Ctrl>S` or the save button
 - Attempt to save the file under a different name on the same folder with `<Ctrl><Shift>S` or the Save As button.

In each case the document should remain open and a suitable infobar appears if not already present.
Cancelling the operation should do that and keep the document
Close without saving should allow the operation to proceed and the changes are lost.

Note : Duplicate the tab - works as normal - the duplicate is created as a writable New Document on the *local* file system.

Repeat the above tests on a local file in a writable folder.  No change from master
Repeat the above tests on a local file in an unwritable folder. No change from master

Repeat the remote unwritable tests only with autosave on.  On opening no infobar appears until a change is made to the file or a save is forced.  Unedited doc can be closed without issue.

With autosave on try to edit and close the document in quick succession in everycase the changes should have been saved when the doc is reopened

### CODE REVIEW

**Comment by jeremypw** [comment]
Closing as #1280 overlaps this one and is simpler.

**Comment by jeremypw** [comment]
Closed wrong PR!

**Review by zeebok — APPROVED** [review]
Code look good! I haven't tested yet but if you feel confident feel free to merge, otherwise I will try to test this as best I can tonight.

**Comment by zeebok** [comment]
Yep what I *could* test does seem to work!

**Pull request merged**
