### PR TITLE
Show git status in sidebar

### PR DESCRIPTION
**Pull request by davidmhewitt**
Depends on #461 for packaging and a new release of granite with the `markup` property on `SourceList.Item`

### CODE REVIEW

**Comment by cassidyjames** [comment]
@davidmhewitt would doing some sort of a dim label next to the title work? Basically just a lighter weight instead of wrapped in parens, I guess.

**Comment by davidmhewitt** [comment]
@cassidyjames Possibly, although the granite sourcelist is super inflexible for that kind of thing. I guess that might be where I have to dedicate my efforts soon.

There are quite a lot of issues in code blocked by issues/inflexibilities of the sourcelist.

**Comment by davidmhewitt** [comment]
This branch is now showing a `(*)` or a `(+)` next to modified or new files as seen by git. This obviously isn't ideal either, since it makes a bit of a mess of renaming them.

But, I feel like that's pretty easily solved by colour instead of text, just got to figure out the best way to apply that to the SourceList.

**Comment by cassidyjames** [comment]
@davidmhewitt I've also added a packaging branch, so hopefully everything's set up right and CI will pass now :crossed_fingers:

**Comment by davidmhewitt** [comment]
It is, yes. I get the impression that some inconsistent things currently happen when you have both added and modified files in the tree, which I need to fix.

However, some UX input into what should happen in that case would be good.

For example, consider the following tree:

- src
  - Widgets
    - WidgetX.vala (modified)
    - WidgetY.vala (added)

Should the little icons on the `src` folder and the `Widgets` folder denote modified, added, or some other state?

**Comment by cassidyjames** [comment]
@davidmhewitt I think modified takes precedence.

**Comment by davidmhewitt** [comment]
As far as I'm concerned, this is no longer in progress and ready to review.

**Comment by cassidyjames** [comment]
This builds and looks great with Granite built from source. I'm not completely sure if that's been released or not, though. Checking into it.

**Comment by cassidyjames** [comment]
Ah, no, that was committed a few days after the latest release. @codygarver can we get a new release of Granite when it's convenient?

**Comment by davidmhewitt** [comment]
New granite version released, no longer blocked.

**Comment by cassidyjames** [comment]
Fixes #133

**Pull request merged**
