### PR TITLE
Make symbol outline aware of follow-system-style setting

### LINKED ISSUE #1263: Symbol outline does not respect system style
### What Happened?

The theme color of the Symbol outline pane doesn't fallow the system dark style preference. Instead, it's background color is whatever the theme color was before toggling on the "Follow system style" toggle.
image

### Steps to Reproduce

1. Open Code while the system is in dark mode
2. Switch it's theme to Light or Elementary light
3. Switch on the Follow system style preference
4. Notice that while the whole app switches it's colors to dark, the symbol outline panel will stay with light background

### Expected Behavior

The background color should change.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #1263 

Just copied the corresponding code from DocumentView.

### CODE REVIEW

**Comment by Marukesu** [comment]
I think this is missing a check for when the system style changes, no?

**Comment by jeremypw** [comment]
@Marukesu Thanks for pointing that out! I will not have time to fix immediately so converting to draft.

**Comment by jeremypw** [comment]
Made use of the `style-changed` signal to avoid repeating some code and ensure style of outline and document match.

**Review by Marukesu — APPROVED** [review]
code works as expected.

**Pull request merged**
