### PR TITLE
Flatpak: Use OpenURI Portal to launch external apps

### PR DESCRIPTION
**Pull request by Marukesu**
Opening as draft because there isn't a libportal package on focal, however i can update the PR to use conditional compilation if perferred. 

it's functional with project folders added via the terminal and the add project folder button.

### CODE REVIEW

**Comment by jeremypw** [comment]
@Marukesu Am I right in thinking that `libportal` is now available in Odin?

**Comment by Marukesu** [comment]
@jeremypw I can't see it with `apt list 'libportal*`.

However, I was thinking in making an alternative PR calling the DBus interface directly like in elementary/calendar#681

It's basically an exchange of dependencies form `libportal` to `gdk-x11-3.0` and `gdk-wayland-3.0`.

**Comment by jeremypw** [comment]
The gdk dependencies sound like they may be provided by the elementary flatpak platform? Not sure how to find out exactly what that provides. Anyway sounds like a good idea.

**Comment by jeremypw** [comment]
Superceded by #1162

**Pull request closed without merging**
