### PR TITLE
ChooseProjectButton: ellipsize long radio items

### PR DESCRIPTION
**Pull request by danrabbit**
Make sure we also handle ellipsizing radio items

Change ellipsize mode to middle to disambiguate cases like `switchboard-plug-foo` where relevant information is at the beginning and end

### CODE REVIEW

**Comment by jeremypw** [comment]
I guess this is required as a consequence of constraining the width of the popover to the width of the button.  Is there any downside to allowing the popover to expand to show the full project name?

**Comment by jeremypw** [comment]
I agree with the middle ellipsize for th button though.

**Comment by jeremypw** [comment]
This is how it looks if you remove the size group and instead use the same character with for the search entry as for the button label.

With a long project name
ExpandPopoverLong
Without a long project name
ExpandPopoverShort

**Review by jeremypw — COMMENTED** [review]
I have suggested an alternative - I think it would be better to see the full name in the popover.

**Comment by danrabbit** [comment]
@jeremypw Removed the sizegroup instead, but kept middle ellipsize :+1:

**Review by jeremypw — APPROVED** [review]
:+1:

**Pull request merged**
