### PR TITLE
Save and restore sidebar open setting

### LINKED ISSUE #757: Sidebar doesn't remember to stay close on re-open
#89  Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When working on only one file, I keep the sidebar closed. But does not stay close when re-opening Code.

### To Reproduce
1. Click on the gear icon in titlebar
2. Click on **Toggle Sidebar**
3. Close Code
4. Re-open Code

### Expected behavior
Closing sidebar, closing Code, on re-open the sidebar should not be opened

### Screenshots or screen recordings
https://i.imgur.com/WIE3SmR.gifv

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #757

### CODE REVIEW

**Comment by jeremypw** [comment]
Doh!

**Comment by jeremypw** [comment]
OK, thanks - it seemed to work for me but I probably have different sidebar content.  I'll investigate further and come up with a more reliable solution.

**Comment by jeremypw** [comment]
Hopefully this solution is more reliable on other systems.

**Comment by rajitsingh** [comment]
As I've reported [here](https://github.com/elementary/code/issues/757#issuecomment-643776043), the issue has resurfaced once again with the Code update to version 3.4.1.

**Comment by jeremypw** [comment]
This needs a rewrite due to other changes to the master.

**Comment by quequotion** [comment]
The sooner the better!

**Comment by jeremypw** [comment]
Closed for rewrite

**Pull request closed without merging**
