### PR TITLE
Bind visibility of sidebar and choose_project_button

### PR DESCRIPTION
**Pull request by jeremypw**
Partially addresses #1082 by hiding the Project Chooser button in the header whenever the sidebar is hidden.

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
Can we add a revealer here so we get a nice animation instead of just binding to visible?

**Comment by jeremypw** [comment]
OK, I'll give it a try - do you want a revealer for the sidebar as well? I don't think it has one.

**Comment by jeremypw** [comment]
@danrabbit I've now used a revealer for the chooseproject button.  Using one for the sidebar proved problematic as it is in a Paned so I've left it for now.

**Review by cassidyjames — APPROVED** [review]
Nice. Even without the sidebar animation, this feels pretty slick.

**Pull request merged**
